Duplicated tests files error with SonarQube 4.5
ERROR: Error during Sonar runner execution
Caused by: File [relative=x.cs, abs=y.Tests/x.cs] can't be indexed
twice. Please check that inclusion/exclusion patterns produce disjoint
sets for main and test files